@echo off
ren ega.drv ega.tmp
ren ega.old ega.drv
ren ega.tmp ega.old
ren ultima.com ultima.tmp
ren ultima.old ultima.com
ren ultima.tmp ultima.old
ren avatar.exe avatar.tmp
ren avatar.old avatar.exe
ren avatar.tmp avatar.old
ren compassn.ega compassn.tmp
ren compassn.old compassn.ega
ren compassn.tmp compassn.old
ren courage.ega courage.tmp
ren courage.old courage.ega
ren courage.tmp courage.old
ren honesty.ega honesty.tmp
ren honesty.old honesty.ega
ren honesty.tmp honesty.old
ren honor.ega honor.tmp
ren honor.old honor.ega
ren honor.tmp honor.old
ren humility.ega humility.tmp
ren humility.old humility.ega
ren humility.tmp humility.old
ren justice.ega justice.tmp
ren justice.old justice.ega
ren justice.tmp justice.old
ren key7.ega key7.tmp
ren key7.old key7.ega
ren key7.tmp key7.old
ren love.ega love.tmp
ren love.old love.ega
ren love.tmp love.old
ren rune_0.ega rune_0.tmp
ren rune_0.old rune_0.ega
ren rune_0.tmp rune_0.old
ren rune_1.ega rune_1.tmp
ren rune_1.old rune_1.ega
ren rune_1.tmp rune_1.old
ren rune_2.ega rune_2.tmp
ren rune_2.old rune_2.ega
ren rune_2.tmp rune_2.old
ren rune_3.ega rune_3.tmp
ren rune_3.old rune_3.ega
ren rune_3.tmp rune_3.old
ren rune_4.ega rune_4.tmp
ren rune_4.old rune_4.ega
ren rune_4.tmp rune_4.old
ren rune_5.ega rune_5.tmp
ren rune_5.old rune_5.ega
ren rune_5.tmp rune_5.old
ren sacrific.ega sacrific.tmp
ren sacrific.old sacrific.ega
ren sacrific.tmp sacrific.old
ren spirit.ega spirit.tmp
ren spirit.old spirit.ega
ren spirit.tmp spirit.old
ren start.ega start.tmp
ren start.old start.ega
ren start.tmp start.old
ren stoncrcl.ega stoncrcl.tmp
ren stoncrcl.old stoncrcl.ega
ren stoncrcl.tmp stoncrcl.old
ren truth.ega truth.tmp
ren truth.old truth.ega
ren truth.tmp truth.old
ren valor.ega valor.tmp
ren valor.old valor.ega
ren valor.tmp valor.old
ren cove.tlk cove.tmp
ren cove.old cove.tlk
ren cove.tmp cove.old
ren lcb.tlk lcb.tmp
ren lcb.old lcb.tlk
ren lcb.tmp lcb.old
ren minoc.tlk minoc.tmp
ren minoc.old minoc.tlk
ren minoc.tmp minoc.old
ren skara.tlk skara.tmp
ren skara.old skara.tlk
ren skara.tmp skara.old
ren yew.tlk yew.tmp
ren yew.old yew.tlk
ren yew.tmp yew.old
