#!/usr/bin/bash
# Container build script for xu4 Linux & Windows packages.

VERSION=DR-$(git rev-parse --short HEAD)

if [ ! -s project.tar.gz ]; then
	sed -i "s/DR-1.0/${VERSION}/" project.b
	copr -a -t mingw gpu_render:true
fi


TIME=$(date +%H%M%S)
SCRIPT=build-$TIME
ID=${SCRIPT}
HDIR=/tmp
CDIR=/tmp
ARC_DIR=/tmp/xu4-${VERSION}
SDK_DIR=dist/sdk

if [ ! -d ${SDK_DIR} ]; then
	echo "Library archive ${SDK_DIR} not found!"
	echo "Run \"make -C dist cbuild-sdks\""
	exit
fi

clean_dir () {
	if [ -d "$1" ]; then rm -rf "$1"/*; else mkdir -p "$1"; fi
}

case $1 in
windows)
	echo '
  unzip /tmp/allegro-x86_64-w64-mingw32-gcc-10.2.0-posix-seh-static-5.2.7.0.zip
  mv allegro usr
  unzip /tmp/boron-x86_64-w64-mingw32-static-2.0.7.zip
  unzip /tmp/faun-x86_64-w64-mingw32-static-0.1.0.zip -d usr
  mkdir u4
  cd u4
  tar xf /tmp/project.tar.gz
  copr -t mingw make_util:false
' >$HDIR/${SCRIPT}

	podman run -d -it --name=$ID xu4/f33-mingw /bin/bash || exit
	podman cp ${SDK_DIR}/allegro-x86_64-w64-mingw32-gcc-10.2.0-posix-seh-static-5.2.7.0.zip $ID:$CDIR
	podman cp ${SDK_DIR}/boron-x86_64-w64-mingw32-static-2.0.7.zip $ID:$CDIR
	podman cp ${SDK_DIR}/faun-x86_64-w64-mingw32-static-0.1.0.zip $ID:$CDIR
	podman cp project.tar.gz $ID:$CDIR
	podman cp $HDIR/${SCRIPT} $ID:$CDIR/${SCRIPT}
	podman exec -it -u build $ID /bin/bash $CDIR/${SCRIPT}
	podman cp $ID:/home/build/u4/xu4.exe /tmp/xu4.exe-$TIME || exit

	# Build zip archive.
	if [ "$2" != "-b" ]; then
		clean_dir ${ARC_DIR}
		FN=`readlink -f ${SDK_DIR}/allegro-faun-dll.tar.bz2`
		tar xf $FN -C ${ARC_DIR}
		cp /tmp/xu4.exe-$TIME ${ARC_DIR}/xu4.exe
		cp render.pak Ultima-IV.mod ${ARC_DIR}
		cp COPYING ${ARC_DIR}/COPYING.txt
		cp README.md ${ARC_DIR}/README.txt
		cd ${ARC_DIR%/*}; zip -r xu4-win32.zip ${ARC_DIR##*/}
	fi
	;;

linux)
	echo '
  tar xjf /tmp/boron-x86_64-static-2.0.7.tar.bz2
  tar xjf /tmp/faun-x86_64-static-0.1.0.tar.bz2 -C boron --strip-components=1
  mkdir u4
  cd u4
  tar xf /tmp/project.tar.gz
  copr make_util:false sdk_dir:%../boron
' >$HDIR/${SCRIPT}

	podman run -d -it --name=$ID xu4/f33-gcc /bin/bash || exit
	podman cp ${SDK_DIR}/boron-x86_64-static-2.0.7.tar.bz2 $ID:$CDIR
	podman cp ${SDK_DIR}/faun-x86_64-static-0.1.0.tar.bz2 $ID:$CDIR
	podman cp project.tar.gz $ID:$CDIR
	podman cp $HDIR/${SCRIPT} $ID:$CDIR/${SCRIPT}
	podman exec -it $ID /bin/bash $CDIR/${SCRIPT}
	podman cp $ID:/home/build/u4/xu4 /tmp/xu4-$TIME || exit

	# Build archive.
	if [ "$2" != "-b" ]; then
		clean_dir ${ARC_DIR}
		cp /tmp/xu4-$TIME ${ARC_DIR}/xu4
		cp render.pak Ultima-IV.mod COPYING dist/setup ${ARC_DIR}
		cp README.md ${ARC_DIR}/README
		cp dist/README.linux-dr ${ARC_DIR}/README-Linux
        mkdir ${ARC_DIR}/desktop
		cp icons/xu4.png dist/xu4.desktop ${ARC_DIR}/desktop
		tar czf /tmp/xu4-linux.tar.gz -C ${ARC_DIR%/*} ${ARC_DIR##*/}
	fi
	;;

*)
	echo "Usage: $0 {linux|windows} [-b]"
	echo -e '\nOptions:'
	echo '  -b    Build binary only; do not create archive.'
	exit 1
esac

echo "$SCRIPT done!"
podman stop $ID
